version: '3.4'
services:
  identifier:
    image: semtech/mu-identifier:1.8.1
    ports:
      - 80:80
    links:
      - dispatcher:dispatcher
    environment:
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
    labels:
      - "logging=true"
    restart: always
  dispatcher:
    image: semtech/mu-dispatcher:latest
    links:
      - resource:resource
      - validation:validation
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    ports:
      - 8890:8890
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  validation:
    build: ../
    volumes:
      - ./config:/config
    ports:
      - 8090:80
    environment:
      DEFAULT_APPLICATION_PROFILE_PATH: "file:/config/applicationProfile.ttl"
      SPARQL_ENDPOINT: "http://db:8890" # todo change that
      MAX_REQUEST_SIZE: "512MB"
      MAX_FILE_SIZE: "512MB"
      JAVA_OPTS: "-Xms512m -Xmx512m"
    restart: always
  resource:
    image: semtech/mu-cl-resources:1.20.0
    links:
      - db:database
    volumes:
      - ./config/resources:/config
    restart: always